graph TB
    开始((开始)) --> 对话["对话<br/>LLM+绑定工具"]
    对话 --> 工具判断{"工具判断"}
    工具判断 -- "有" --> 工具["工具执行<br/>continuity_check<br/>ai_trace_check<br/>pacing_control<br/>hook_opening<br/>dialogue_craft<br/>scene_description<br/>emotion_scene<br/>action_scene<br/>suspense_twist<br/>narrative_viewpoint"]
    工具判断 -- "无" --> 结束((结束))
    工具 --> 对话
